Added logos
quarkiverse/quarkus-quinoa pull request #324
Opened 2023-04-16 14:57 UTC by melloware

2023-04-16 15:41 UTC, shivam-sharma7 requested changes
Fix Path of images

2023-04-16 15:41 UTC, shivam-sharma7 commented on README.md
> +<img src="https://github.com/quarkiverse/quarkus-quinoa/blob/main/docs/modules/ROOT/assets/images/quarkus.svg" height="50" ><img src="https://github.com/quarkiverse/quarkus-quinoa/blob/main/docs/modu
image does not appear in README.md

![image](https://user-images.githubusercontent.com/91419219/232323999-f37d7581-53d6-49ce-817c-5f63e6cad69e.png)
****

2023-04-16 15:41 UTC, melloware commented
Yeah I don't think it will work until the images are actually there and merged with this PR.

2023-04-16 15:42 UTC, melloware commented
@shivam-sharma7 if you want to submit this same PR I can approve it.  I just can't approve and merge my own PR's.

2023-04-16 15:46 UTC, shivam-sharma7 commented
> @shivam-sharma7 if you want to submit this same PR I can approve it. I just can't approve and merge my own PR's.

no problem will wait till @ia3andy does not approves this PR.

2023-04-26 09:59 UTC, ia3andy approved these changes
Thanks

2023-04-26 09:59 UTC, merged