[#470] Developer profile
quarkiverse/quarkus-quinoa pull request #471
Opened 2023-08-09 03:34 UTC by shivam-sharma7

## Describe your changes

## Fixes Issue: #470

 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2023-08-09 12:27 UTC, melloware requested changes

2023-08-09 12:27 UTC, melloware commented on pom.xml
> +        <name>melloware</name>
```suggestion
        <name>Emil Lefkof</name>
```

2023-08-09 12:40 UTC, melloware approved these changes

2023-08-09 12:48 UTC, merged

2023-08-16 08:28 UTC, ia3andy commented
@shivam-sharma7 could we please have less noisy PRs please, this is giving me a hard time following the real stuff. You are contributing a lot of docs and managing PRs but please if you want to be and stay included in the developers you need to contribute real code with your own logic.

We keep you in this list for now, but I urge you to fix code bugs or create real features with code and stop creating PRs just for the stats.

2023-08-16 10:23 UTC, shivam-sharma7 commented
@ia3andy my bad! Okay