Define npm install by quinoa
quarkiverse/quarkus-quinoa pull request #548
Opened 2023-10-12 04:47 UTC by shivam-sharma7

## Describe your changes

## Fixes Issue

 

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

2023-10-12 12:18 UTC, melloware requested changes

2023-10-12 12:18 UTC, melloware commented on docs/modules/ROOT/pages/advanced-guides.adoc
> +<3> Define the version of Npm to install
```suggestion
<3> Define the version of NPM to install
```

2023-10-13 11:47 UTC, melloware approved these changes

2023-10-13 11:47 UTC, merged

2023-10-18 17:55 UTC, melloware commented
@shivam-sharma7 can you translate "Now" in Hindi for me?  For example if `"today": "आज",` is for Today what about the Current Time.  In english we say the time "NOW" is.  I am updating my PF translations

2023-10-18 21:22 UTC, shivam-sharma7 commented
@melloware `अभि`

2023-10-18 21:23 UTC, melloware commented
Thank you!