NextJS 14 `next export` has been removed
quarkiverse/quarkus-quinoa pull request #572
Opened 2023-11-25 13:05 UTC by shivam-sharma7

## Describe your changes
check-https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#version-history

2023-11-25 15:14 UTC, melloware commented
I think we need to update the docs too: https://docs.quarkiverse.io/quarkus-quinoa/dev/web-frameworks.html#nextjs-config

and test it. Someone else on another forum I am on was saying Next14 doesn't generate an `index.html` like the old export did which Quinoa needs?

2023-12-05 04:20 UTC, shivam-sharma7 commented
the next export command is deprecated in Next.js 14. Starting with this version, we should use the "output": "export" option in your `next.config.js` file to generate static exports.

Here is an example of my merged PR- https://github.com/tailwarden/komiser/pull/1217/files

2023-12-05 12:40 UTC, melloware commented
Yes so we need to update the docs for Next.JS or check for the `output: export` and throw an error if not found.

2023-12-05 12:40 UTC, melloware requested changes
See comments

2023-12-05 12:47 UTC, shivam-sharma7 commented
@melloware We don't need to check I think because that is totally depend on user deployment.So we need to update the docs.

2023-12-05 13:05 UTC, melloware commented
When I tried this before Quinoa does NOT work unless its in this mode so we have to check and make it required for Next.   You can't use Next with Quinoa without the static export mode.

2023-12-05 13:14 UTC, melloware requested changes

2023-12-05 13:14 UTC, melloware commented on docs/modules/ROOT/pages/web-frameworks.adoc
> +And in new version of next.js you need to add the following property in `next.config.js` file:
```suggestion
In Next.js 14+ you need to add the following property in `next.config.js` file:
```

2023-12-08 15:17 UTC, merged