[Fix/727] Change location for get angular application configuration
quarkiverse/quarkus-quinoa pull request #722
Opened 2024-07-21 20:47 UTC by yatho

## Describe your changes

I have changed the detection of angular configuration application. Before we used the package.json's name. Now we get the application available in angular.json file. If multiple applications exist in this configuration, an exception will be thrown. Users have to help quinoa to know which one must be build in this context.

## Fixes Issue
closes #721 
 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

2024-07-21 21:16 UTC, melloware approved these changes

2024-07-21 21:17 UTC, melloware commented
Thank I will merge and release tomorrow.

2024-07-22 09:34 UTC, ia3andy requested changes

2024-07-22 10:22 UTC, yatho commented on deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFramework.java
> +                        .orElseThrow(() -> new RuntimeException(
Done

2024-07-22 10:29 UTC, ia3andy approved these changes

2024-07-22 10:33 UTC, yatho commented
@melloware issue #723 will be fixed by this correction because if custom build-dir is provided then, I don't do anything. But I don't understand why if custom uiDir is provided, angular.json file is not found. I am checking that point.

2024-07-22 10:59 UTC, yatho commented
This PR fix #723 issue. Because if ui-dir is provided in configuration, in this version we don't get angular.json file.

2024-07-22 11:21 UTC, melloware approved these changes

2024-07-22 11:21 UTC, merged